# Automatically generated by: ros2nix --flake
{ lib, buildRosPackage, rclpy }:
buildRosPackage rec {
  pname = "ros-rolling-antenna-pkg";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ rclpy ];

  meta = {
    description = "Tracking antenna ROS node";
    license = with lib.licenses; [ "AGPL-3.0-only" ];
  };
}
